server:
  port: 8887

spring:
  cloud:
     config:
       server:
         git:
           uri: https://github.com/hahajjy/jjy-config.git
           search-paths: java-config
       label: master
     bus:
       trace:
         enabled: true
       enabled: true
  application:
    name: @pom.artifactId@
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: bus-refresh

