server:
  port: 8887

spring:
  application:
    name: @pom.artifactId@
  cloud:
     config:
       server:
         git:
           uri: https://github.com/hahajjy/jjy-config.git
           search-paths: java-config
       label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
